### ISSUE TITLE
getting below exception while using your super SEED job

### ISSUE THREAD

**Issue by er-jagdish** [figaw/freestyle-to-pipeline-jenkins#2]
[EnvInject] - Loading node environment variables.
Building in workspace /var/jenkins_home/workspace/Jseed
ERROR: no Job DSL script(s) found at pipelineJob('hello-pipeline-inline') {
Finished: FAILURE

**Comment by figaw** [comment]
Is this still a problem? Could you provide some information about what you're trying to do or which steps you took before you got the error?
